### ISSUE TITLE
pipenv not found

### ISSUE THREAD

**Issue by GurRonenExplorium** [serverless/github-action#27]
Hey,

I have a project with dependencies managed with Pipfile.

I tried using this action to deploy, yet had an error:
  Error: pipenv not found! Install it with 'pip install pipenv'.
Added a step before to install pipenv but it isn't picking up

What is the solution to this?

**Comment by ollisala** [comment]
Hi, Same problem here.

**Comment by GurRonenExplorium** [comment]
Thanks for the workaround @ollisala
