### ISSUE TITLE
Upgrade to latest version of serverless

### ISSUE THREAD

**Issue by bhumijgupta** [serverless/github-action#44]
Currently in the dockerfile we are locking serverless install to v2.1 while the current version is v2.17.1
https://github.com/serverless/github-action/blob/3ffc018507c4970c8ed1112c37e0f896a5b886b5/Dockerfile#L14

This would cause people using newer features to get unknown directive/rule warning and incompatibility issues.
The 2 ways I can think of solving this is:-
1. Upgrade the dockerfile to version 2.17.0, but that would require manual upgrading whenever new version is released
2. Change it to `RUN npm i -g serverless` without locking to specific version

I think second option is better. I am willing to open a PR for any of the case.

**Comment by DavideViolante** [comment]
Thanks, I agree that is not convenient to upgrade the version each time, so I [committed](https://github.com/serverless/github-action/commit/a0cec0c331a05b468e093fb1f4b8e051fb628076) a change to install `v2.x`, in that way it will install the latest v2 version but won't install a future potentially breaking v3 version.
