### ISSUE TITLE
Updating to v2.18.0 breaks recommended plugin install

### ISSUE THREAD

**Issue by nevins-b** [serverless/github-action#52]
the recommended setup from #28 no longer works due to bash missing in the image

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
```

**Comment by What1s1ove** [comment]
Is there any way I can fix this?

**Comment by nevins-b** [comment]
adding `RUN apk add bash` should install bash into this container and allow this to continue to work

**Comment by anandg112** [comment]
or you can use the entrypoint as:
`entrypoint: /bin/sh`

as the new base image is alpine
