### ISSUE TITLE
serverless/github-action@v2

### ISSUE THREAD

**Issue by hemantfaze** [serverless/github-action#62]
This is not working ! We have a major release in 1 hour, can't deploy any of services because of this

**Comment by hemantfaze** [comment]
I have forked and changed the version for now. Probably will use the forked version from now on.

**Comment by DavideViolante** [comment]
This does not work?
```
      uses: serverless/github-action@v2
```

Try if this works and let me know, thanks:
```
      uses: serverless/github-action@v2.18.0
```

**Comment by DavideViolante** [comment]
It should now be solved, thanks for the issue. I thought the `v1` was referring to a tag, but in fact it was referring to a branch. The v2 branch was not existing, so it was not working.
I also pushed v3 branch aligned with master for being able to write `github-action@v3` (recommended).
In general never use the master version of an action.
