### ISSUE TITLE
The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by timkellogg** [serverless/github-action#9]
I'm trying to deploy a serverless function through github actions but receive the following error: 

```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

I've setup the secrets on github and I've also manually deployed locally using:

```
serverless deploy --key {key} --secret {secret}
``` 

And that successfully creates the application.

Any advice?

**Edit**

I believe it's related to permissions within AWS so I will close.

**Comment by AdeOpe** [comment]
@timkellogg how did you solve this?
