### ISSUE TITLE
Please add support for serverless v4

### ISSUE THREAD

**Issue by lxandrexl** [serverless/github-action#91]
Don't forget to provide support here, we developers who use github actions would be very grateful.

**Comment by ryanlawson** [comment]
I have a PR open to address this and some other improvements. In the meantime I have them published here: https://github.com/ryanlawson/serverless-github-action

**Comment by bernier** [comment]
@ryanlawson do you know by any chance when the PR will be ready?
I tried the repo you linked but I'm getting the error "s:cli-error-handler: Configuration file not found in directory "/github/workspace/backend""
My only option right now is to downgrade my project to Serverless 3 and use my old setup.
Thanks

**Comment by skierkowski** [comment]
V4 is already supported but you have to specify the version, `serverless/github-action@v4`. You can see it in action in the [aws-ai-stack](https://github.com/serverless/aws-ai-stack/blob/main/.github/workflows/main.yml) example project.
