### ISSUE TITLE
Unable to find Route by key POST /<route-name> within the provided RouteSettings

### ISSUE THREAD

**Issue by Philrobots** [serverless/github-action#95]
Error message :

`Unable to find Route by key POST /<route-name> within the provided RouteSettings`

Description: 

Deployment failed because I deleted a route inside my serverless.yml file, and it keeps failing even though the route does not exist anymore on AWS API Gateway

What should I do ?

# 
What's weird is that my AWS deployment works, but the github actions checks failed.

**Comment by ryanlawson** [comment]
Are you able to deploy locally with the same `sls` command?

Looks like an issue with Serverless and not the Github Action based on this [thread](https://github.com/serverless/serverless/issues/12776#issuecomment-2529445682). The action just calls `serverless` in the container.

**Comment by Philrobots** [comment]
You are right, probably a serverless action
